#!/bin/sh

ignoredirs="\.|\.git|freebsd|homedir"
homestuff="$(ls -a homedir/ | grep -Ev '^\.$|^\.\.$')" # FIXME single regex

mkdir -p ${HOME}/.config

find . -type d -maxdepth 1 | xargs -r basename | grep -Ev ${ignoredirs} |
xargs -r stow -v

for h in ${homestuff}; do
	test -d "${h}" && mkdir -pv ${HOME}/${h}
	cp -rv homedir/${h} ${HOME}/
done

cp -v \
	freebsd/src-env.conf \
	/etc/
cp -v freebsd/rc.conf.desktop /etc/rc.conf
cp -v freebsd/loader.conf.desktop /boot/loader.conf
cp -v freebsd/.login_conf ${HOME}/ && cap_mkdb ${HOME}/.login_conf
