#!/bin/sh

cp -vf \
	/etc/src-env.conf \
	/etc/rc.local \
	${HOME}/.login_conf \
	freebsd/
cp -vf /etc/rc.conf freebsd/rc.conf.desktop
cp -vf /boot/loader.conf freebsd/loader.conf.desktop

mkdir -pv homedir
cp -rv \
	${HOME}/.fonts \
	${HOME}/.gitconfig \
	${HOME}/.password-store \
	${HOME}/.sfeed \
	${HOME}/.gnupg \
	${HOME}/.ssh \
	${HOME}/.vim \
	homedir/
